# Generated by Django 5.2 on 2025-04-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
